name: loveknowsnodistance
favicon: null
layout_spectrum: 0.27099296846427023
typography_spectrum: 0.863177431980148
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.10966659849509597
  lightness: 0.4959267664235085
  saturation: 0.5742063738871366
  rhythmicContrast: 0.02537812665104866
purpose: []
